<?php
// https://docs.google.com/document/d/1wZ4iLe92_w6UjKk_eC34A6x1X3NRC32ywiiYo0E6f04/edit?usp=sharing
function fossee_institute_permission(){
    return array(
        "view_workshop" => array(
            "title" => t("View Workshop"),
            "description" => t("Allows users to view workshop.")
        ),
        "access college data"=>array(
            'title'=>t('View College Profile Data'),
            'description'=>t('Allow users to view collge profile data')
        )
    );
}
function fossee_institute_profiles_menu(){
    $menu = array();
    $menu['cProfiles'] = array(
        'title'=>'College Profiles',
        'description'=>'College Profile',
        'page callback'=>'fossee_institute_profiles_page',
        'access callback'=>true
    );
    $menu['workshop/view'] = array(
        "title" => "Workshop",
        "page callback" => "fossee_institute_profiles_workshop",
        "access arguments" => array(
            "view_workshop"
        ),
        'access callback'=>true,
        "type" => MENU_CALLBACK
    );
    $menu["lab-data"] = array(
        "title" => "",
        "page callback" => "fossee_get_data",
        'page arguments' => array(
            2
        ),
        "access arguments" => array(
            "access college data"
        ),
        "type" => MENU_CALLBACK,
        'access callback'=>true
    );
    $menu["textbook"] = array(
        "title" => "",
        "page callback" => "fossee_get_data",
        'page arguments' => array(
            2
        ),
        "access arguments" => array(
            "access college data"
        ),
        "type" => MENU_CALLBACK,
        'access callback'=>true
    );
    $menu['clg/autocomplete'] = array(
        'title' => 'Autocomplete for cities',
        'page callback' => 'fossee_clg_autocomplete',
        'access arguments' => array('use autocomplete'),  //or whatever permission makes sense
        'type' => MENU_CALLBACK,
        'access callback'=>true
      );
    return $menu;
}

function fossee_clg_autocomplete($str){
    $matches = array();
    db_query("USE fossee_new");
    $query = db_query('SELECT * FROM clg_names WHERE name LIKE :args;',array(
        ':args'=>'%'.$str.'%'
    ));
    $rows = $query->fetchAll();
    // // save the query to matches
    foreach ($rows as $row) {
      $matches[$row->name] = check_plain($row->name);
    }
    // Return the result to the form in json
    return drupal_json_output($matches);
}

function fossee_get_data($id = 0,$type = ''){
    $out = '';
    $qstr = 'SELECT * FROM '.$type.'.lab_migration_proposal WHERE id = '.$id;
    $query = db_query($qstr);
    $rows = $query->fetchAll();
    $rl = count($rows);
    if($rl > 0){
        drupal_add_css(drupal_get_path('module','fossee_institute_profiles').'/fossee_profiles.css');
        if($type == 'scilab') $ltype = 'Scilab';
        else if($type == 'esim') $ltype = 'eSim';
        else if($type == 'dwsim_2015') $ltype = 'DWSIM';
        else if($type == 'openmodelica') $ltype = 'Open Modelica';
        else if($type == 'cfd_2015') $ltype = 'OpenFOAM';
        else $ltype = 'Others';

        $out = '<table class="table table-bordered table-hover">';
        $out .= '<tr><td><b>Title</b></td><td>'.$rows[0]->lab_title.'</td></tr>';        
        $out .= '<tr><td><b>Lab Type</b></td><td>'.$ltype.'</td></tr>';        
        $out .= '<tr><td><b>By</b></td><td>'.$rows[0]->name_title.' '.$rows[0]->name.'</td></tr>';        
        $out .= '<tr><td><b>Department</b></td><td>'.$rows[0]->department.'</td></tr>';        
        $out .= '<tr><td><b>University</b></td><td>'.$rows[0]->university.'</td></tr>';        
        $out .= '<tr><td><b>City</b></td><td>'.$rows[0]->city.'</td></tr>';
        $out .= '<tr><td><b>Pin Code</b></td><td>'.$rows[0]->pincode.'</td></tr>';        
        $out .= '<tr><td><b>State</b></td><td>'.$rows[0]->state.'</td></tr>';        
        $out .= '<tr><td><b>Country</b></td><td>'.$rows[0]->country.'</td></tr>'; 
        
        if($rows[0]->approval_status == 3)     
            $out .= '<tr><td><b>Progress</b></td><td>Completed</td></tr>';      
        else if($rows[0]->approval_status == 5)
            $out .= '<tr><td><b>Progress</b></td><td>Under Observation</td></tr>';
        else
            $out .= '<tr><td><b>Progress</b></td><td>In Progress</td></tr>';
        
        if($rows[0]->solution_provider_name != ''){
            $out .= '<tr><td><b>Solution Provider Name</b></td><td>'.$rows[0]->solution_provider_name_title.' '.$rows[0]->solution_provider_name.'</td></tr>';      
            $out .= '<tr><td><b>Solution Provider Department</b></td><td>'.$rows[0]->solution_provider_department.'</td></tr>';      
            $out .= '<tr><td><b>Solution Provider University</b></td><td>'.$rows[0]->solution_provider_university.'</td></tr>';
        }
        $out .= '</table>';
        if($rows[0]->approval_status == 3){
            if($type == 'scilab')
                $out .= '<a href="http://scilab.in/lab_migration_run/'.$rows[0]->id.'" target="_blank" id="rButton">Main Website</a>';
            if($type == 'esim')
                $out .= '<a href="http://esim.fossee.in/lab_migration_run/'.$rows[0]->id.'" target="_blank" id="rButton">Main Website</a>';                
        }
    }
    return $out;
}

function fossee_institute_profiles_workshop($wid = 0){
    $query = db_query('SELECT * FROM workshop WHERE w_id = :args',array(':args'=>$wid));
    $rows = $query->fetchAll();
    $out = '<b>NO Data Find!</b>';
    if(count($rows) > 0){
        drupal_add_js(drupal_get_path('module','fossee_institute_profiles').'/fossee_profiles.js');
        drupal_add_css(drupal_get_path('module','fossee_institute_profiles').'/fossee_profiles.css');
        
        $out = '<table class="table table-bordered table-hover">';
        $out .= '<tr><td><b>Name</b></td><td>'.$rows[0]->w_name.'</td></tr>';
        $out .= '<tr><td><b>Start Date</b></td><td>'.$rows[0]->startdate.'</td></tr>';
        $out .= '<tr><td><b>End Date</b></td><td>'.$rows[0]->enddate.'</td></tr>';
        $out .= '<tr><td><b>No. of Participants</b></td><td>'.$rows[0]->no_of_participant.'</td></tr>';
        $out .= '<tr><td><b>Venue</b></td><td>'.$rows[0]->venue.'</td></tr>';
        if($rows[0]->event_link != '')
            $out .= '<tr><td><b>Events Website</b></td><td>'.$rows[0]->event_link.'</td></tr>';    
        $out .= '<tr><td><b>Details</b></td><td>'.$rows[0]->body.'</td></tr>';
        $query = db_query('SELECT * FROM workshop_images WHERE w_id = :args',array(':args'=>$wid));
        $rows = $query->fetchAll();
        $rl = count($rows);
        $Fpage = drupal_get_normal_path(url()); // Get the front url
        if($rl > 0)     $out .= '<tr><td><b>Images</b></td><td>';
        foreach($rows as $row){
            if(strpos($row->path,'events_images') !== false)
            $out .= '<img src="'.$Fpage.str_replace('/Site/fossee_drupal','',$row->path).'" alt="IMG"  class="wimg" onclick="viewImage(this)"/>';
            else $out .= '<img src="'.$Fpage.'events_images/'.str_replace('/Site/fossee_drupal','',$row->path).'" alt="IMG" class="wimg" onclick="viewImage(this)"/>';
        }    
        if($rl > 0)
            $out .= '</td></tr>';
        $out .= '</table>';
        if($rl > 0)$out .= '<div id="VIewBox"></div>';
    }
    return $out;
}

function fossee_institute_profiles_display($val){
    $lab = '';  // Lab Migration Html
    $state = ''; // State of the colege
    $country = ''; // Country of the college
    $city = ''; // City of the college
    $work = ''; // Worshop html
    $text = ''; // Text book html
    $i = 1; // Increnet variable
    $query = db_query('SELECT * FROM workshop WHERE venue LIKE :args;',array(':args'=>'%'.$val.'%'));
    $rows = $query->fetchAll();
    $Fpage = drupal_get_normal_path(url()); // Get the front url

    foreach($rows as $row){
        $work .= '<a href="'.$Fpage.'workshop/view/'.$row->w_id.'" target="_blank">'.$i.' > '.$row->w_name.'</a><br>';
        $i++;
    }
    // Lab Migration Proposal
    $i = 1;
    $query = db_query('SELECT * FROM scilab.lab_migration_proposal WHERE university LIKE :arg',array(':arg'=>'%'.$val.'%'));
    $rows = $query->fetchAll();
    foreach($rows as $row){
        $lab .= '<a href="'.$Fpage.'lab-data/scilab/'.$row->id.'" target="_blank">'.$i.' > '.$row->lab_title.'</a><br>';
        if(IS_EMPTY($state) || IS_EMPTY($city) || IS_EMPTY($country)){    
            $state = $row->state;
            $city = $row->city;
            $country = $row->country;
        }
        $i++;
    }

    $query = db_query('SELECT * FROM esim.lab_migration_proposal WHERE university LIKE :arg',array(':arg'=>'%'.$val.'%'));
    $rows = $query->fetchAll();
    foreach($rows as $row){
        $lab .= '<a href="'.$Fpage.'lab-data/esim/'.$row->id.'" target="_blank">'.$i.' > '.$row->lab_title.'</a><br>';
        if(IS_EMPTY($state) || IS_EMPTY($city) || IS_EMPTY($country)){    
            $state = $row->state;
            $city = $row->city;
            $country = $row->country;
        }
        $i++;
    }
    $query = db_query('SELECT * FROM openmodelica.lab_migration_proposal WHERE university LIKE :arg',array(':arg'=>'%'.$val.'%'));
    $rows = $query->fetchAll();
    foreach($rows as $row){
        $lab .= '<a href="'.$Fpage.'lab-data/openmodelica/'.$row->id.'" target="_blank">'.$i.' > '.$row->lab_title.'</a><br>';
        if(IS_EMPTY($state) || IS_EMPTY($city) || IS_EMPTY($country)){    
            $state = $row->state;
            $city = $row->city;
            $country = $row->country;
        }
        $i++;
    }
    $query = db_query('SELECT * FROM dwsim_2015.lab_migration_proposal WHERE university LIKE :arg',array(':arg'=>'%'.$val.'%'));
    $rows = $query->fetchAll();
    foreach($rows as $row){
        $lab .= '<a href="'.$Fpage.'lab-data/dwsim_2015/'.$row->id.'" target="_blank">'.$i.' > '.$row->lab_title.'</a><br>';
        if(IS_EMPTY($state) || IS_EMPTY($city) || IS_EMPTY($country)){    
            $state = $row->state;
            $city = $row->city;
            $country = $row->country;
        }
        $i++;
    }
    $query = db_query('SELECT * FROM cfd_2015.lab_migration_proposal WHERE university LIKE :arg',array(':arg'=>'%'.$val.'%'));
    $rows = $query->fetchAll();
    foreach($rows as $row){
        $lab .= '<a href="'.$Fpage.'lab-data/cfd_2015/'.$row->id.'" target="_blank">'.$i.' > '.$row->lab_title.'</a><br>';
        if(IS_EMPTY($state) || IS_EMPTY($city) || IS_EMPTY($country)){    
            $state = $row->state;
            $city = $row->city;
            $country = $row->country;
        }
        $i++;
    }

    /***************************** Text book********************* */
    $i = 1;
    $query = db_query('SELECT pe.book as book,pe.author as author,pe.id as id FROM scilab.textbook_companion_proposal po left join scilab.textbook_companion_preference pe on po.id = pe.id WHERE university LIKE :arg AND pe.id IS NOT NULL',array(':arg'=>'%'.$val.'%'));
    $rows = $query->fetchAll();
    foreach($rows as $row){
        $text .= '<a href="'.$row->id.'" target="_blank">'.$i.' > '.$row->book.' By '.$row->author.'</a><br>';
        $i++;
    }
    
    $query = db_query('SELECT pe.book as book,pe.author as author,pe.id as id FROM esim.textbook_companion_proposal po left join esim.textbook_companion_preference pe on po.id = pe.id WHERE university LIKE :arg AND pe.id IS NOT NULL',array(':arg'=>'%'.$val.'%'));
    $rows = $query->fetchAll();
    foreach($rows as $row){
        $text .= '<a href="'.$row->id.'" target="_blank">'.$i.' > '.$row->book.' By '.$row->author.'</a><br>';
        $i++;
    }
    
    $query = db_query('SELECT pe.book as book,pe.author as author,pe.id as id FROM dwsim_2015.textbook_companion_proposal po left join dwsim_2015.textbook_companion_preference pe on po.id = pe.id WHERE university LIKE :arg AND pe.id IS NOT NULL',array(':arg'=>'%'.$val.'%'));
    $rows = $query->fetchAll();
    foreach($rows as $row){
        $text .= '<a href="'.$row->id.'" target="_blank">'.$i.' > '.$row->book.' By '.$row->author.'</a><br>';
        $i++;
    }
    
    $query = db_query('SELECT pe.book as book,pe.author as author,pe.id as id FROM openmodelica.textbook_companion_proposal po left join openmodelica.textbook_companion_preference pe on po.id = pe.id WHERE university LIKE :arg AND pe.id IS NOT NULL',array(':arg'=>'%'.$val.'%'));
    $rows = $query->fetchAll();
    foreach($rows as $row){
        $text .= '<a href="'.$row->id.'" target="_blank">'.$i.' > '.$row->book.' By '.$row->author.'</a><br>';
        $i++;
    }

    $query = db_query('SELECT pe.book as book,pe.author as author,pe.id as id FROM cfd_2015.textbook_companion_proposal po left join cfd_2015.textbook_companion_preference pe on po.id = pe.id WHERE university LIKE :arg AND pe.id IS NOT NULL',array(':arg'=>'%'.$val.'%'));
    $rows = $query->fetchAll();
    foreach($rows as $row){
        $text .= '<a href="'.$row->id.'" target="_blank">'.$i.' > '.$row->book.' By '.$row->author.'</a><br>';
        $i++;
    }

    $query = db_query('SELECT pe.book as book,pe.author as author,pe.id as id FROM or_fossee.textbook_companion_proposal po left join or_fossee.textbook_companion_preference pe on po.id = pe.id WHERE university LIKE :arg AND pe.id IS NOT NULL',array(':arg'=>'%'.$val.'%'));
    $rows = $query->fetchAll();
    foreach($rows as $row){
        $text .= '<a href="'.$row->id.'" target="_blank">'.$i.' > '.$row->book.' By '.$row->author.'</a><br>';
        $i++;
    }
    /*********************************** Display Data ******************/
    if(IS_EMPTY($state)) $state = "----";
    if(IS_EMPTY($city)) $city = "----";
    if(IS_EMPTY($country)) $country = "----";

    $out .= '<div id="cProfile">';
    $out .= '<label id="cName">'.$val.'</label><br>';
    $out .= '( <b>Country</b> : '.$country;
    $out .= '&nbsp;&nbsp;<b>State</b> : '.$state;
    $out .= '&nbsp;&nbsp;<b>City</b> : '.$city.' )';
    $out .= '<br><label>Lab Migration</label><br>';
    if($lab != '')
        $out .= $lab;
    else $out .= 'No Lab migration Done!<br>';
    $out .= '<label>Textbook Companion</label><br>';
    if($text != '')
        $out .= $text;
    else $out .= "No Textbook Companion!<br>";
    $out .= '<label>Workshops</label><br>';
    if($work != '')
        $out .= $work;
    else $out .= 'No Workshop Done!';
    $out .= '</div>';
    return $out;
}

// Check Wether it The string is empty , none or 0
function IS_EMPTY($val){
    return ($val === '' || $val === 'None' || $val === '0');
}

function fossee_institute_profiles_page(){
    drupal_add_js(drupal_get_path('module','fossee_institute_profiles').'/fossee_profiles.js');
    drupal_add_css(drupal_get_path('module','fossee_institute_profiles').'/fossee_profiles.css');
    
    if(isset($_GET['c'])){
        return fossee_institute_profiles_display(str_replace('-',' ',$_GET['c']));
    }else return drupal_get_form('fossee_profiles_form');
}

function fossee_profiles_form($form,&$formState){
    $form['clg'] = array(
        '#type' => 'textfield',
        '#title' => '',
        '#maxlength' => 70,
        '#prefix' => '<div class="container-inline">',
        '#autocomplete_path' => 'clg/autocomplete'
    );
    $form['submit'] = array(
        '#type'=>'button',
        '#value'=>'Q',
        '#suffix'=>'</div>',
        '#ajax'=>array(
            'callback'=>'fossee_search'
        )
    );
    return $form;
}

function fossee_search($form,&$formState){
    $clg = ($formState['values']['clg'] != '')?$formState['values']['clg']:'NODATAFOUNDINDATABASE';
    $commands[] = ajax_command_invoke(NULL, 'search', array($clg));
	return array('#type' => "ajax", '#commands' => $commands);
}