<?php
/*
 * foss_type
 * lab_migration_proposal -> university
 * textbook_companion_proposal
 * workshop
 * selfworkshop,events_training,events_academiccenter,events_city,events_state
 *
 */
// https://docs.google.com/document/d/1wZ4iLe92_w6UjKk_eC34A6x1X3NRC32ywiiYo0E6f04/edit?usp=sharing
function fossee_institute_profiles_menu(){
    $menu = array();
    $menu['cProfiles'] = array(
        'title'=>'College Profiles',
        'description'=>'College Profile',
        'page callback'=>'fossee_institute_profiles_page',
        // 'page arguments'=>array('fossee_institute_profiles_form'),
        'access callback'=>true
    );
    return $menu;
}

function fossee_institute_profiles_form($form,&$formState){
    // db_set_active('default');
    // $fQuery = db_query('SELECT * FROM foss_type');
    // $foss_type = $fQuery->fetchAll();
    // dpm($foss_type);
    // $country = 'India';

    // $form['states'] = array(
    //     '#type' => 'select',
    //     '#title' => t('State'),
    //     '#options' => array(
    //     ),
    //     '#description' => t('Select a State'),
    // );
    
        $form['clgName'] = array(
            '#title'=>'Enter the College Name',
            '#type'=>'textfield'
        );

    return $form;
}

function fossee_institute_profiles_display($val){
    $out = '';
    
}

function fossee_institute_profiles_page(){
    drupal_add_js(drupal_get_path('module','fossee_institute_profiles').'/fossee_profiles.js');
    
    if(isset($_GET['c'])){
        return fossee_institute_profiles_display($_GET['c']);
    }
    
    
    
    $tmp = '<b>Enter The College Name :</b><br>';
    $tmp .= '<input type="text" id="clgName" onkeyup="AddTOList(this)" keydown="clearSgst(event)">';

    db_set_active('Scilab');
    $query = db_query('SELECT DISTINCT university FROM lab_migration_proposal;');
    $rows = $query->fetchAll();
    $tmp .= '<script> var sci_lab_m = '.json_encode($rows).'</script>';
    
    $query = db_query('SELECT DISTINCT university FROM textbook_companion_proposal;');
    $rows = $query->fetchAll();
    $tmp .= '<script> var sci_lab_text = '.json_encode($rows).'</script>';

    
    $tmp .= '<div id="suggest"></div>';
    $tmp .= '<div id="result"></div>';
    // dpm($rows);
    return $tmp;
}